name: Maven Release Artifact Validation

on:
  push:
    branches:
      - 'release-*'
  pull_request:
    branches:
      - 'release-*'

env:
  MVN_ARGS: -e -ntp -B -V -Dgpg.skip -Djacoco.skip -Pwarn-log -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.dependency=warn -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=5
  SPARK_COMMON_MODULES: hudi-spark-datasource/hudi-spark,hudi-spark-datasource/hudi-spark-common

jobs:
  validate-release-maven-artifacts:
    runs-on: ubuntu-latest
    if: true
    env:
      HUDI_VERSION: 1.1.1
      MAVEN_BASE_URL: 'https://repo1.maven.org/maven2'
    strategy:
      matrix:
        include:
          - scalaProfile: 'scala-2.13'
            flinkProfile: 'flink2.0'
            sparkProfile: 'spark3.5'
            sparkRuntime: 'spark3.5.1'
          - scalaProfile: 'scala-2.13'
            flinkProfile: 'flink1.20'
            sparkProfile: 'spark3.5'
            sparkRuntime: 'spark3.5.1'
          - scalaProfile: 'scala-2.13'
            flinkProfile: 'flink1.19'
            sparkProfile: 'spark3.5'
            sparkRuntime: 'spark3.5.1'
          - scalaProfile: 'scala-2.12'
            flinkProfile: 'flink1.18'
            sparkProfile: 'spark3.4'
            sparkRuntime: 'spark3.4.3'
          - scalaProfile: 'scala-2.12'
            flinkProfile: 'flink1.17'
            sparkProfile: 'spark3.3'
            sparkRuntime: 'spark3.3.4'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: IT - Bundle Validation - OpenJDK 8
        env:
          FLINK_PROFILE: ${{ matrix.flinkProfile }}
          SPARK_PROFILE: ${{ matrix.sparkProfile }}
          SPARK_RUNTIME: ${{ matrix.sparkRuntime }}
          SCALA_PROFILE: ${{ matrix.scalaProfile }}
        run: |
          ./packaging/bundle-validation/ci_run.sh hudi_docker_java8 $HUDI_VERSION openjdk8 "" $MAVEN_BASE_URL
      - name: IT - Bundle Validation - OpenJDK 11
        env:
          FLINK_PROFILE: ${{ matrix.flinkProfile }}
          SPARK_PROFILE: ${{ matrix.sparkProfile }}
          SPARK_RUNTIME: ${{ matrix.sparkRuntime }}
          SCALA_PROFILE: ${{ matrix.scalaProfile }}
        run: |
          ./packaging/bundle-validation/ci_run.sh hudi_docker_java11 $HUDI_VERSION openjdk11 "" $MAVEN_BASE_URL
      - name: IT - Bundle Validation - OpenJDK 17
        env:
          FLINK_PROFILE: ${{ matrix.flinkProfile }}
          SPARK_PROFILE: ${{ matrix.sparkProfile }}
          SPARK_RUNTIME: ${{ matrix.sparkRuntime }}
          SCALA_PROFILE: ${{ matrix.scalaProfile }}
        run: |
          ./packaging/bundle-validation/ci_run.sh hudi_docker_java17 $HUDI_VERSION openjdk17 "" $MAVEN_BASE_URL
