name: Update Template

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
    paths:
      - .github/PULL_REQUEST_TEMPLATE.md

jobs:
  check-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ensure script is updated
        run: git diff --name-only remotes/origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...remotes/origin/${CI_COMMIT_REF_NAME} | grep -c scripts/pr_compliance.py || exit 1